version: '3.8'

services:
  server-node:
    container_name: server-node
    image: server-node:1.0.0
    deploy:
      replicas: 1
    restart: always
    ports:
      - 3106:80
    volumes:
      - "/etc/node-typscript/config:/etc/config"
      - "/etc/node-typscript/data:/app/data"
    network_mode: bridge
